### ISSUE TITLE
Couldn't find `solver()`

### ISSUE THREAD

**Issue by stineb** [walkeranthonyp/MAAT#13]
Hi there,
Congratulations to this fantastic tool. Seems like a cool thing and I've just starting to have a look around. I read in Walker et al., 2018 GMD, Appendix A4:
"In MAAT, these equations are combined into a single function (called the solver function in MAAT; [...])"
I searched for the string `solver`, as well as `uniroot` in the src/ subdirectory but couldn't find anything. Can you point me to the right place (where gs, Cc, and A are simultaneously solved)?
Thanks!
beni

**Comment by walkeranthonyp** [comment]
Hi Beni,

Thanks for your interest in maat. Am about to hit AGU and have been in
meetings all weekend so apologies for the delay and brevity. I'd be glad to
chat about this more.

Go to the system models directory in src. In there you will find several
directories that relate to a system model. In the leaf directory you'll
find everything needed for the leaf model. leaf_functions.R is where you'll
find the solver etc. leaf_object.R gives you the data structure and general
methods. leaf_system_functions.R is where the the overall structure of the
leaf model lives.

Bye for now.

Cheers,

Anthony

**Comment by stineb** [comment]
Thanks Anthony,
I'll have a look and hope to catch up at AGU!
Beni


Am 10.12.2018 um 09:37 schrieb walkeranthonyp <notifications@github.com<mailto:notifications@github.com>>:

Hi Beni,

Thanks for your interest in maat. Am about to hit AGU and have been in
meetings all weekend so apologies for the delay and brevity. I'd be glad to
chat about this more.

Go to the system models directory in src. In there you will find several
directories that relate to a system model. In the leaf directory you'll
find everything needed for the leaf model. leaf_functions.R is where you'll
find the solver etc. leaf_object.R gives you the data structure and general
methods. leaf_system_functions.R is where the the overall structure of the
leaf model lives.

Bye for now.

Cheers,

Anthony

**Comment by walkeranthonyp** [comment]
Yeah, I just saw you're speaking here. Would be great to catch up!
