### ISSUE TITLE
Automatically restarting MCMC simulation

### ISSUE THREAD

**Issue by abbeyjohnson1** [walkeranthonyp/MAAT#26]
When I've needed to manually restart the MCMC process, I've been using the `mcmc_prior_none` function in wrapper_functions_mcmc.R to hardcode `.$dataf$pars` from the last accepted proposal in `.$dataf$pars_array` when `j == .$wpars$mcmc_maxiter`. This becomes the fake "prior," basically the first iteration `j == 1`, for the restart.

_Basic outline of the process to be automated:_
  * when `j == .$wpars$mcmc_maxiter` 
  * check whether or not convergence has been reached
  * i.e. check if `R_hat[i] < 1.2 for i = 1:d`, where d is the total number of parameters
  * alternatively, can also check if `.$dataf$conv_check[(.$wpars$mcmc_maxiter / .$wpars$mcmc_check_iter), i] < 1.2 for i = 2:(d + 1)` 
  * if this is not true, convergence has not been reached
    * need to restart the MCMC process (basically reset `j = 1`) but instead of using the prior distribution type specified as a `wpars` parameter, use the most recent accepted proposal 
`.$dataf$pars_array[ , , .$wpars$mcmc_maxiter]`  (and corresponding likelihood) as the first sample for the restart
  * if this is true
    * check to make sure it is not "pseudo-convergence"
      * if it is "pseudo-convergence," need to restart the MCMC process
    * check to make sure that more posterior (post-convergence) samples are not needed for analysis or plotting (i.e., an instance if convergence happened in the last 100 iterations or so)
      * if more samples are needed, restart the MCMC process
      * when restarting in this instance, it would be be nice to somehow store/keep/append the some of the outputs from the MCMC simulation if that's possible (`.$dataf$obs, .$dataf$out_mcmc, .$dataf$prop_storage, and .$dataf$conv_check`)  
  * if not pseudo-convergence and no more posterior samples are needed, then convergence has been reached, and no need to restart

_Some potentially tricky algorithmic bits:_ 

_Pseudo-convergence_
The R-statistic of Gelman and Rubin is a bit funky in that it initially starts at a low number (below 1.2) and stays low for awhile. If the MCMC algorithm is stopped during this time, it numerically looks like convergence has been reached, but in reality the algorithm hasn't had enough time to converge. I call this pseudo-convergence. The R-statistic needs to grow above 1.2 for all parameters, and then eventually drop back down for true convergence to be declared. Depending on the complexity of the model and the length of `.$wpars$mcmc_maxiter`, it might be easy to get trapped by pseudo-convergence.

_Adapting the selection of crossover probabilites (p_CR)_
In a single MCMC run, the `p_CR` values are adapted for a certain number of iterations (default is 25% of `.$wpars$mcmc_maxiter`). If a MCMC process is being restarted, then we would not want to re-re-adjust the already adapted pCR values. So if restarting, it would be nice to somehow switch `.$wpars$mcmc_adapt_pCR` from true to false. It would also be nice to read in the adapted `p_CR` values from the last run and initialize them for the restart run when initializing `.$dataf$pars`.

_Boundary handling_
Currently, the `boundary_handling_set` function is where `.$mcmc$boundary_min` and `.$mcmc$boundary_max` values are being set. The way I've currently structured it is by reading in the values from the init file depending on what type of prior is specified. When there is an MCMC restart and no prior is specified, this function won't work the way it is currently structured. So it would be nice if it's possible to read in `.$mcmc$boundary_min` and `.$mcmc$boundary_max` from the first run and initialize them when doing a restart.

**Comment by abbeyjohnson1** [comment]
**Rough outline of updated restart process:**

See photo of whiteboard doodle for reference and array structures.

![maat_doodle](https://user-images.githubusercontent.com/39961811/74052792-90268b80-49a8-11ea-8be3-53e6a97acd04.jpg)

Have one output file `mcmc_out` that will be overwritten and appended to with each manual restart. Have multiple history files (`mcmc_history_1`, `mcmc_history_2`, etc) that are automatically generated. These history files will contain "discarded" samples, likelihoods, model evals etc. in case we need them during post-processing.  

We will need new counters like `burnin_j` in addition to an outlier counter that will also be outputted in the `mcmc_out` RDS file.

The outlier detection and convergence diagnostic subroutines use the last 50% of all MCMC samples to do their calculations, and this is what will be stored in `mcmc_out` in addition to the rest of the corresponding information in the output RDS file. This "last 50%" will change with each new sample, so what is being stored in `mcmc_out` will be changing and growing accordingly. The first 50% of data will be stored in the history files.

_Side note 1:_ The MCMC run functions will be re-indexed, and so will the outlier and convergence diagnostic functions. 

_Side note 2:_ There will need to be some funky arithmetic to calculate which samples to use in the outlier and convergence functions, because of how we are now storing things, we will no longer be able to take the total number of samples and divide by two. 

_Side note 3:_ There is also a small bug in the restart code. If it is the first MCMC simulation where a prior distribution is being used, the code tries to read from an empty RDS file instead of call the prior calculation function. This can be fixed with an `else` clause in `run_MAAT.R`.

**Comment by walkeranthonyp** [comment]
@abbeyjohnson1 how much of this issue is still current? Does #29 replace it? If so can you close it, if not can you refresh which pieces still need addressing. e.g. perhaps *Side note 3* is still relevant

**Comment by abbeyjohnson1** [comment]
@walkeranthonyp To the best of my knowledge, this issue has been addressed. And issue #29 already contains the elements of this issue that still need to be addressed. I just haven't closed this issue yet, because we're still debugging the restart process, and everything detailed here hasn't been fully tested yet if that makes sense. But I can close this if you'd like me to!

**Comment by walkeranthonyp** [comment]
OK, that sounds good. Keep it open for now and let me know if you see anything here that needs dealing with still (for now I'm going to continue working on #29).

**Comment by walkeranthonyp** [comment]
This should all now have been handled with the bugfixing of the restart and the subsequent development. The one remaining issue is the "pseudo-convergence." Currently there is no automatic convergence handling so can revisit if/when that gets developed.
