### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by serbinsh** [walkeranthonyp/MAAT#32]
An issue to track newer dependencies not part of the install_dependencies.R file

10-4-25-253:src sserbin$ Rscript unit_testing.R
Error in library(deSolve) : there is no package called ‘deSolve’
Calls: source ... source -> source -> withVisible -> eval -> eval -> library
Execution halted

I will go ahead and provide a PR

**Comment by serbinsh** [comment]
Here is the PR for consideration: https://github.com/walkeranthonyp/MAAT/pull/33

**Comment by walkeranthonyp** [comment]
Thanks.
