### ISSUE TITLE
run_met errors (undefined variable)

### ISSUE THREAD

**Issue by Daryl-YANG** [walkeranthonyp/MAAT#35]
test_aci (from leaf unit_testing) and other aci models threw below error: 

Error in 1:.$dataf$lm : argument of length 0 

Seems something messed up in run_met. there is an incorrect call of variable 'lm', which does not exist in the dataf. 

run_met:
function(.,l) {

  if(!is.null(.$init)) .$init()
  t(vapply(1:.$dataf$lm, .$run_met1, .$dataf$mout )) 
}

**Comment by walkeranthonyp** [comment]
Thanks, I'll take a look and get back to you.

**Comment by walkeranthonyp** [comment]
OK, this should be fixed now. Let me know if not, otherwise please mark as resolved. Thanks for the feedback!
