### ISSUE TITLE
metdata is ignored unless it has a EM_PAR_8100_x column

### ISSUE THREAD

**Issue by nocollier** [walkeranthonyp/MAAT#44]
and values are positive.

https://github.com/walkeranthonyp/MAAT/blob/551f6d4bb077d78773049f4269c9ff018bf403f3/src/run_MAAT.R#L547

Users can circumvent by commenting out L547-8. No rush on a fix, just wanted to log a workaround for the meantime.

**Comment by walkeranthonyp** [comment]
Thanks @nocollier for finding this -- this is now fixed with [commit 64aab65 today](https://github.com/walkeranthonyp/MAAT/commit/64aab654e2cf85178510136d991917155480028d) as well as a subsequent bug in the functions that combine input and output to write to file once the ensemble has executed.
