### ISSUE TITLE
Question: Leaf Rd plots show ceiling of respiration rates in PEcAn-MAAT runs

### ISSUE THREAD

**Issue by serbinsh** [walkeranthonyp/MAAT#9]
@walkeranthonyp see attached

![screen shot 2018-08-28 at 9 26 50 am](https://user-images.githubusercontent.com/3067369/44725904-82c35d00-aaa4-11e8-8f8c-c145f93e8622.png)

I have noticed that in my MAAT runs in PEcAn that Rd often shows this pattern.  Is this expected?  Perhaps something related to my maat configuration options?

**Comment by walkeranthonyp** [comment]
My guess is that a peaked T response function is being used for Rd. You can check the function that is used for Rd by looking in the ```<runid>_setup_static.xml```. Look in the ```fnames``` list and search for ```rd```. Rd T response can be set to be exactly that of vcmax, or it can be independent. By default the rd T response is dependent on the vcmax T response, i.e. the response scalars are identical. By default the vcmax T response is a modified Arrhenius.       

... though I must say the cutoff is pretty strange. What do the T data look like?

**Comment by serbinsh** [comment]
Have to run to a lab meeting and will send more later but for now here is the config in my pecan.xml

```
    <config>
          <mod_obj>leaf</mod_obj>
          <leaf>
              <fnames>
                  <vcmax>'f_vcmax_constant'</vcmax>
                  <jmax>'f_jmax_constant'</jmax>
                  <rd>'f_rd_constant'</rd>
                  <rs>'f_rs_ball1987'</rs>
                  <etrans>'f_j_farquharwong1984'</etrans>
                  <tcor_asc>
                        <vcmax>'f_tcor_asc_Arrhenius'</vcmax>
                        <jmax>'f_tcor_asc_Arrhenius'</jmax>
                        <rd>'f_tcor_asc_Q10'</rd>
                        <tpu>'f_tcor_asc_Arrhenius'</tpu>
                  </tcor_asc>
                  <tcor_des>
                        <vcmax>'f_tcor_des_modArrhenius'</vcmax>
                        <jmax>'f_tcor_des_modArrhenius'</jmax>
                        <rd>'f_tcor_des_cox2001'</rd>
                  </tcor_des>
              </fnames>
              <env>
                  <ca_conc>400</ca_conc>
              </env>
          </leaf>
      </config>
```

Looks like I setup cox for the deactivation, so maybe thats it?

**Comment by walkeranthonyp** [comment]
Yes, could be, but you also need to check in ```<runid>_setup_static.xml``` that:
```
   <tcor_dep>
        <rd>'f_tcor_dep_independent'</rd>
        ... 
      </tcor_dep>
```
the default is:
```
   <tcor_dep>
        <rd>'f_tcor_dep_dependent'</rd>
        ... 
      </tcor_dep>
```
Which means it will be the same as vcmax scaling.

**Comment by serbinsh** [comment]
aha here is an example <runid>_setup_static.xml

```
      <tcor_asc>
        <vcmax>'f_tcor_asc_Arrhenius'</vcmax>
        <jmax>'f_tcor_asc_Arrhenius'</jmax>
        <tpu>'f_tcor_asc_Arrhenius'</tpu>
        <rd>'f_tcor_asc_Q10'</rd>
        <gstar>'f_tcor_asc_quadratic_bf1985'</gstar>
        <tau>'f_tcor_asc_Q10'</tau>
        <Kc>'f_tcor_asc_Arrhenius'</Kc>
        <Ko>'f_tcor_asc_Arrhenius'</Ko>
      </tcor_asc>
      <tcor_des>
        <vcmax>'f_tcor_des_modArrhenius'</vcmax>
        <jmax>'f_tcor_des_modArrhenius'</jmax>
        <tpu>'f_tcor_des_modArrhenius'</tpu>
        <rd>'f_tcor_des_cox2001'</rd>
      </tcor_des>
      <tcor_dep>
        <tpu>'f_tcor_dep_dependent'</tpu>
        <rd>'f_tcor_dep_dependent'</rd>
      </tcor_dep>
```

**Comment by walkeranthonyp** [comment]
@serbin sorry for being slack on this issue. The Rd function is peaked in this simulation (using the COx style decrease with increasing temp). Lemme know if this is stilll an issue or we can close. Cheers.

**Comment by serbinsh** [comment]
Ahhh...so the "cap" or peak on this is expected ?  In that case, can be closed

**Comment by walkeranthonyp** [comment]
Yes, I think that makes sense right? It's a peaked response so that would impose a cap. If you really want to dig into it you could do and Rd ~ air/leaf T plot.
